spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/realworld}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-root.yml
